# -*- coding: utf-8 -*-
"""intraday.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xOSeGToH4mVWVE7L3EaFdka6exvF8f-Q
"""
import pygsheets
import pandas as pd
from pyhomebroker import HomeBroker
import datetime

scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
gc = pygsheets.authorize(service_file='')
sheetOut=gc.open("Arb_Sheet")

broker = 

dni = ''
user = ''
password = ''
hb = HomeBroker(int(broker))
hb.auth.login(dni=dni, user=user, password=password, raise_exception=True)


today = datetime.date.today()
stoday = today.strftime("%Y-%m-%d")

mep_df=pd.DataFrame(columns=['date',"AL29D",'AL30','AL30D','mepAL30','GD29D','GD30','GD30D','mepGD30'])


AL30_df=hb.history.get_intraday_history('AL30')
AL30_df.date=AL30_df.date.dt.strftime("%H:%M")
AL30_df.drop_duplicates(subset=['date'],inplace=True)

mep_df.date=AL30_df.date
mep_df.set_index("date",inplace=True)

AL30_df = AL30_df[["date","close","open"]].copy()
AL30_df.columns=["date","AL30","open"]
AL30_df.set_index("date",inplace=True)

AL30D_df=hb.history.get_intraday_history('AL30D')
AL30D_df.date=AL30D_df.date.dt.strftime("%H:%M")
AL30D_df.drop_duplicates(subset=['date'],inplace=True)
AL30D_df = AL30D_df[["date","close"]].copy()
AL30D_df.columns=["date","AL30D"]
AL30D_df.set_index("date",inplace=True)

AL29D_df=hb.history.get_intraday_history('AL29D')
AL29D_df.date=AL29D_df.date.dt.strftime("%H:%M")
AL29D_df.drop_duplicates(subset=['date'],inplace=True)
AL29D_df = AL29D_df[["date","close"]].copy()
AL29D_df.columns=["date","AL29D"]
AL29D_df.set_index("date",inplace=True)

GD30D_df=hb.history.get_intraday_history('GD30D')
GD30D_df.date=GD30D_df.date.dt.strftime("%H:%M")
GD30D_df.drop_duplicates(subset=['date'],inplace=True)
GD30D_df = GD30D_df[["date","close"]].copy()
GD30D_df.columns=["date","GD30D"]
GD30D_df.set_index("date",inplace=True)

GD30_df=hb.history.get_intraday_history('GD30')
GD30_df.date=GD30_df.date.dt.strftime("%H:%M")
GD30_df.drop_duplicates(subset=['date'],inplace=True)
GD30_df = GD30_df[["date","close"]].copy()
GD30_df.columns=["date","GD30"]
GD30_df.set_index("date",inplace=True)

GD29D_df=hb.history.get_intraday_history('GD29D')
GD29D_df.date=GD29D_df.date.dt.strftime("%H:%M")
GD29D_df.drop_duplicates(subset=['date'],inplace=True)
GD29D_df = GD29D_df[["date","close"]].copy()
GD29D_df.columns=["date","GD29D"]
GD29D_df.set_index("date",inplace=True)

mep_df.update(AL30_df)
mep_df.update(AL30D_df)
mep_df.update(AL29D_df)
mep_df.update(GD30D_df)
mep_df.update(GD30_df)
mep_df.update(GD29D_df)
mep_df=mep_df.fillna(method="ffill")
mep_df=mep_df.fillna(method="bfill")
mep_df.mepGD30=mep_df.GD30/mep_df.GD30D
mep_df.mepAL30=mep_df.AL30/mep_df.AL30D
mep_df.reset_index(inplace=True)

mep_df=mep_df.round(3)
mep_df.date=stoday +" "+ mep_df.date+":02"
wks = sheetOut.worksheet_by_title("Intra2")
wks.clear(start='A5', end='q400')
wks.set_dataframe(mep_df,(1,1) )
